
title: 高志中学校サイエンス部
description: 福井県立高志中学校にある部活、サイエンス部のホームページ
language: ja
long: ja
location: ja
encding: utf-8
baseurl: "/"
url: "https://koshiscience.github.io"
github_username:  koshiscience
repository: koshiscience/koshiscience.github.io

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll/tagging

tag_feed_layout: tag_page
tag_feed_dir: tag


defaults:
  -
    scope:
      path: ""
    values:
      image: "/img/2020-01-27-koshischool.jpg"
      layout: "default"
