source "https://rubygems.org"

gem "jekyll"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jemoji"
gem "jekyll-mentions"
gem "jekyll-redirect-from"
gem "jekyll-github-metadata"
gem "jekyll-seo-tag"
gem "jekyll-tagging"
gem "webrick"
